### ISSUE TITLE
Video preview grid 3x3 not working

### ISSUE THREAD

**Issue by karlmvb** [fupdec/Adult-Video-Database#35] opened 2021-03-15 16:41 UTC
Video preview is enable in AVDB and working fine but Video preview grid 3x3 feature not working\generating in video \ performance page,

**Comment by fupdec** [comment] 2021-03-15 19:03
the creation of a grid occurs in real time when you open a page with videos.  each grid takes about 5 seconds depending on the size of the video and the power of the CPU.  When all the grids are ready, the page will automatically re-render and you should see grids instead usual picture preview.  to check whether it works or not, try opening a page with as few videos as possible.

also ffmpeg.exe is needed for this feature.

**Comment by fupdec** [comment] 2021-03-15 19:03
the creation of a grid occurs in real time when you open a page with videos.  each grid takes about 5 seconds depending on the size of the video and the power of the CPU.  When all the grids are ready, the page will automatically re-render and you should see grids instead usual picture preview.  to check whether it works or not, try opening a page with as few videos as possible.

also ffmpeg.exe is needed for this feature.

**Comment by karlmvb** [comment] 2021-03-15 19:55
I have the ffmpeg installed, and preview works fine as i passed with the mouse it starts the video, i also use VLC as built-in player that permits to open and change the thumb frame, but the video preview grid 3x3 feature don't, i have tried to enable & disable several times the option. And as recommended i tried to open a video page and limit with filter the number of videos to try the automatically re-render, but it does not work.

**Comment by fupdec** [comment] 2021-03-15 22:09
sorry to confuse you.  after all, this bug has nothing to do with user actions.  will be fixed in the next Windows release.

**Comment by karlmvb** [comment] 2021-03-16 01:00
Strange... the feature started to work after a while... thanks for the support

**Comment by fupdec** [comment] 2021-03-16 01:27
Anyway I will check it.

**Comment by karlmvb** [comment] 2021-03-31 17:47
Hello again, this feature is still not working properly (at least for me) on version 0.7.3

When i open the AVDB app and open a performance video list or even the video tag, it start running a background job, and when i open a new video list it start another... and another, but all of them stays on loop:

![Capture](https://user-images.githubusercontent.com/69876968/113187565-e875b800-9250-11eb-97c9-03f87d264224.PNG)

I don't know if this is related but I looked on the Windows Event viewer and every time i open the app AVDB on a video list it gives and Event ID: 10016; DistributedCOM error, that could indicate permissions of some sort, and it seems that maybe it stays stuck on trying to generate the 3x3 preview grid but it cant and opening other videos lists it increases the background jobs but it not gives additionally Event ID: 10016 on windows event viewer.

Thanks in advanced for the support

**Comment by fupdec** [comment] 2021-04-01 14:15
I need more information. Open devtools with CTRL+SHIFT+I, then tab "console" and if there is red text, then paste it here. it may contain file paths. be sure that you have removed personal information from the inserted text.

**Comment by karlmvb** [comment] 2021-04-01 14:38
Ok, i see two red texts displaying errors. it follows the output:

[1617287663290.log](https://github.com/fupdec/Adult-Video-Database/files/6244356/1617287663290.log)
[1617287669275.log](https://github.com/fupdec/Adult-Video-Database/files/6244357/1617287669275.log)

**Comment by fupdec** [comment] 2021-04-01 14:44
did you add ffmpeg.exe and ffprobe.exe to a folder inside the app?

**Comment by karlmvb** [comment] 2021-04-01 14:47
Yes they are, videos previews & videos playback works nice with the htlm5 player, it also time to time generates the grid 3x3 in some filters or performances, cant understand why only sometimes work.

**Comment by fupdec** [comment] 2021-04-01 14:53
in the future I will make it so that there is no need to worry about the presence of ffmpeg.exe and ffprobe.exe files in the folder. by the log, I still cannot understand what exactly is the reason, I will check again the grid generation.

**Comment by fupdec** [comment] 2021-04-01 15:00
you can also help me with finding the bug. restart the app and open devtools. then use it as usual until you see errors in the console. you need to understand what exactly the bug occurs so that I can reproduce it on my own.

**Comment by karlmvb** [comment] 2021-04-01 15:14
Ok, the use case is simple, i open the app (no errors on console), i go the performance tab, choose one that don´t have grid thumbnails already generated, and after i enter there error on console as show:

[1617289480727.log](https://github.com/fupdec/Adult-Video-Database/files/6244561/1617289480727.log)

![Capture](https://user-images.githubusercontent.com/69876968/113315563-54195d00-9305-11eb-9188-bc2f9db04c23.PNG)

Then if i open more performances the same error displays on console.

**Comment by fupdec** [comment] 2021-04-01 15:33
I think I found a bug. the fix will be in the next release. possibly tomorrow. I have not include a ffprobe in the file that makes the grid. if you don't want to wait, you can try installing ffmpeg as a standalone application.

**Comment by karlmvb** [comment] 2021-04-01 15:36
OK, I was also able to overcome the problem, basically I register the ffmpeg bin folder using the Environmental Variables on Windows to identify where the ffprobe and ffmpeg files are located and puff it worked and started creating the grid.

setx /M PATH "path\to\ffmpeg\bin;%PATH%" 

Thanks for the support

**Comment by fupdec** [comment] 2021-04-01 16:18
this is the right decision. when I manage to make builds for other operating systems, I will try to make it so that users forget about ffmpeg files and can safely use the application.

**Closed by fupdec** 2021-04-01 16:18 UTC
Labels: bug, documentation, question
