### ISSUE TITLE
Cannot add Child Website under website category

### ISSUE THREAD

**Issue by sagar271** [fupdec/Adult-Video-Database#83] opened 2021-06-08 09:01 UTC
Under Website Section, You have added an option to add Child Websites which comes under a network but there is no way to add those. i tried everything but child websites not getting added.
Example - "Brazzers" is a Network which has many child websites like MLIB, MGB, TLIB etc these are not getting added in child websites tab. 
its probably a bug i guess

![Screenshot 2021-06-08 142923](https://user-images.githubusercontent.com/23516708/121155993-f0139780-c865-11eb-8057-9066c16df23a.png)

![Screenshot 2021-06-08 143026](https://user-images.githubusercontent.com/23516708/121156166-1802fb00-c866-11eb-8adf-9872ad9777db.png)

**Comment by fupdec** [comment] 2021-06-08 11:06
I checked how it works. Everything works fine, but there is one caveat. If you make Brazzers a network and add MLIB everything will work fine. If you then open MLIB for editing and turn on the "network" switch, the MLIB will disappear from the Brazzers network. Works as intended. only networks with one child layer are supported. But in any case, I have already made a new system of nested levels and this bug does not make sense. In it, you can add as many nested levels as you like. Will be in the next release. I am closing this task.

**Closed by fupdec** 2021-06-08 11:06 UTC
Labels: bug
